site_name: 1D Burgers PINN Discovery
site_author: Eduardo Furlan
copyright: CC BY 4.0 License
repo_name: "425"
repo_url: http://github.com/efurlanm/425/
docs_dir: docs-src
site_dir: docs
theme:
    name: material
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    palette:
        primary: brown
        accent: brow
    features:
        - header.autohide
plugins:
    - offline  # needs "- privacy" too
    - privacy
    - search
# 2024-03-16 There is a bug where mermaid will always be downloaded and installed, even if it is not used.
markdown_extensions:
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - def_list
    - md_in_html
    - tables
extra_javascript:
    - javascripts/katex/katex.min.js
    - javascripts/katex/contrib/auto-render.min.js
    - javascripts/katex.js
extra_css:
    - javascripts/katex/katex.min.css
    - css/extra.css
exclude_docs: |
    .ipynb_checkpoints
    .git

